"""
Notification Center API
========================
In-app notifications for operational alerts:
- Contract expiring soon
- New complaints
- Missed visits (SLA breach)
- Low completion rate warnings
- System health alerts

Auto-generated by rules, consumed by dashboard.
"""

from datetime import datetime

from flask import Blueprint, g, jsonify, request
from core.security import require_auth, require_role

from kil.db.kelava_db import execute_kelava_query, execute_kelava_query_single

notif_bp = Blueprint("notifications", __name__, url_prefix="/notifications")

_TABLE_ENSURED = False


def _fmt(row):
    if not row:
        return {}
    item = dict(row)
    for k, v in item.items():
        if hasattr(v, "isoformat"):
            item[k] = v.isoformat()
    return item


# ── Get Notifications ──────────────────────────────────────


@notif_bp.route("", methods=["GET"])
@require_auth
def list_notifications():
    """
    Get notifications for current user.
    Query params: unread_only (bool), category, page, per_page
    """
    _ensure_tables()
    user = getattr(g, "current_user", None)
    user_id = user.id if user else None
    role = user.role if user else None

    unread_only = request.args.get("unread_only", "").lower() in ("1", "true")
    category = request.args.get("category")
    page = int(request.args.get("page", 1))
    per_page = min(int(request.args.get("per_page", 20)), 100)
    offset = (page - 1) * per_page

    where = "(n.target_user_id = %s OR n.target_role = %s OR n.target_role = 'all')"
    params = [user_id, role]

    if unread_only:
        where += " AND n.read_at IS NULL"
    if category:
        where += " AND n.category = %s"
        params.append(category)

    params.extend([per_page, offset])

    rows = execute_kelava_query(
        f"""
        SELECT n.*
        FROM enterprise_notifications n
        WHERE {where}
        ORDER BY n.created_at DESC
        LIMIT %s OFFSET %s
        """,
        tuple(params),
    )

    unread_count = execute_kelava_query_single(
        f"""
        SELECT COUNT(*) AS cnt
        FROM enterprise_notifications n
        WHERE (n.target_user_id = %s OR n.target_role = %s OR n.target_role = 'all')
          AND n.read_at IS NULL
        """,
        (user_id, role),
    )

    return jsonify({
        "notifications": [_fmt(r) for r in rows],
        "unread_count": unread_count["cnt"] if unread_count else 0,
        "page": page,
    })


# ── Mark as Read ───────────────────────────────────────────


@notif_bp.route("/<int:notif_id>/read", methods=["POST"])
@require_auth
def mark_read(notif_id: int):
    """Mark a notification as read."""
    _ensure_tables()
    execute_kelava_query(
        "UPDATE enterprise_notifications SET read_at = NOW() WHERE id = %s AND read_at IS NULL",
        (notif_id,),
    )
    return jsonify({"status": "ok"})


@notif_bp.route("/read-all", methods=["POST"])
@require_auth
def mark_all_read():
    """Mark all notifications as read for current user."""
    _ensure_tables()
    user = getattr(g, "current_user", None)
    user_id = user.id if user else None
    role = user.role if user else None

    execute_kelava_query(
        """
        UPDATE enterprise_notifications
        SET read_at = NOW()
        WHERE (target_user_id = %s OR target_role = %s OR target_role = 'all')
          AND read_at IS NULL
        """,
        (user_id, role),
    )
    return jsonify({"status": "ok"})


# ── Generate Notifications (cron or on-demand) ─────────────


@notif_bp.route("/generate", methods=["POST"])
@require_auth
@require_role("admin", "koordinator")
def generate_notifications():
    """
    Scan for operational issues and create notifications.
    Idempotent — won't create duplicate alerts for the same day.
    """
    _ensure_tables()
    today = datetime.now().strftime("%Y-%m-%d")
    created = 0

    # 1. Expiring contracts (within 30 days)
    expiring = execute_kelava_query(
        """
        SELECT k.id, k.no_kontrak, c.name AS customer, k.end_date
        FROM m_customer_kontrak k
        JOIN m_customer c ON c.id = k.id_customer
        WHERE k.is_active = 'YES'
          AND k.end_date BETWEEN CURRENT_DATE AND CURRENT_DATE + 30
        ORDER BY k.end_date
        LIMIT 20
        """
    )
    for exp in expiring:
        created += _create_if_new(
            "contract_expiring",
            f"contract:{exp['id']}:{today}",
            f"Kontrak {exp.get('no_kontrak', 'N/A')} ({exp['customer']}) akan berakhir {exp['end_date']}",
            "koordinator",
            entity_type="contract", entity_id=exp["id"],
            priority="high" if (exp["end_date"] - datetime.now().date()).days <= 7 else "medium",
        )

    # 2. Unresolved complaints older than 3 days
    try:
        old_complaints = execute_kelava_query(
            """
            SELECT comp.id, comp.description, c.name AS customer, comp.created_at
            FROM complaints comp
            LEFT JOIN m_customer c ON c.id = comp.customer_id
            WHERE comp.status NOT IN ('resolved', 'closed')
              AND comp.created_at < NOW() - INTERVAL '3 days'
            ORDER BY comp.created_at
            LIMIT 20
            """
        )
        for comp in old_complaints:
            created += _create_if_new(
                "complaint_overdue",
                f"complaint:{comp['id']}:{today}",
                f"Komplain #{comp['id']} ({comp['customer'] or 'N/A'}) belum selesai sejak {comp['created_at'].strftime('%d/%m')}",
                "koordinator",
                entity_type="complaint", entity_id=comp["id"],
                priority="high",
            )
    except Exception:
        pass

    # 3. Technicians with low completion rate (last 7 days)
    low_performers = execute_kelava_query(
        """
        SELECT rp.id_user, u.fullname,
               COUNT(*) AS planned,
               COUNT(*) FILTER (WHERE rp.status = 'Selesai') AS completed,
               ROUND(COUNT(*) FILTER (WHERE rp.status = 'Selesai')::numeric
                     / NULLIF(COUNT(*), 0) * 100, 1) AS rate
        FROM t_road_plan rp
        JOIN p_user u ON u.id = rp.id_user
        WHERE rp.visit_date >= CURRENT_DATE - 7
        GROUP BY rp.id_user, u.fullname
        HAVING COUNT(*) >= 5
           AND COUNT(*) FILTER (WHERE rp.status = 'Selesai')::numeric / NULLIF(COUNT(*), 0) < 0.6
        ORDER BY rate
        LIMIT 10
        """
    )
    for lp in low_performers:
        created += _create_if_new(
            "low_performance",
            f"low_perf:{lp['id_user']}:{today}",
            f"{lp['fullname']} completion rate rendah: {lp['rate']}% ({lp['completed']}/{lp['planned']} minggu ini)",
            "supervisor",
            entity_type="technician", entity_id=lp["id_user"],
            priority="medium",
        )

    # 4. Yesterday's missed visits
    yesterday = (datetime.now() - __import__("datetime").timedelta(days=1)).strftime("%Y-%m-%d")
    missed = execute_kelava_query_single(
        """
        SELECT COUNT(*) AS cnt
        FROM t_road_plan
        WHERE visit_date::date = %s AND status NOT IN ('Selesai', 'Berjalan')
        """,
        (yesterday,),
    )
    missed_cnt = missed["cnt"] if missed else 0
    if missed_cnt > 0:
        created += _create_if_new(
            "missed_visits",
            f"missed:{yesterday}",
            f"{missed_cnt} kunjungan tidak terlaksana kemarin ({yesterday})",
            "koordinator",
            priority="medium" if missed_cnt < 10 else "high",
        )

    return jsonify({"created": created, "date": today})


# ── Notification Summary (for badge count) ──────────────────


@notif_bp.route("/summary", methods=["GET"])
@require_auth
def notification_summary():
    """Quick unread count per category for badge display."""
    _ensure_tables()
    user = getattr(g, "current_user", None)
    user_id = user.id if user else None
    role = user.role if user else None

    rows = execute_kelava_query(
        """
        SELECT category, COUNT(*) AS cnt
        FROM enterprise_notifications
        WHERE (target_user_id = %s OR target_role = %s OR target_role = 'all')
          AND read_at IS NULL
        GROUP BY category
        """,
        (user_id, role),
    )

    by_category = {r["category"]: r["cnt"] for r in rows}
    total = sum(by_category.values())

    return jsonify({"unread_total": total, "by_category": by_category})


# ── Helpers ─────────────────────────────────────────────────


def _create_if_new(category, dedup_key, message, target_role,
                   target_user_id=None, entity_type=None, entity_id=None,
                   priority="medium"):
    """Create notification only if dedup_key doesn't exist yet."""
    existing = execute_kelava_query_single(
        "SELECT id FROM enterprise_notifications WHERE dedup_key = %s",
        (dedup_key,),
    )
    if existing:
        return 0

    execute_kelava_query(
        """
        INSERT INTO enterprise_notifications
            (category, dedup_key, message, target_role, target_user_id,
             entity_type, entity_id, priority)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """,
        (category, dedup_key, message, target_role, target_user_id,
         entity_type, entity_id, priority),
    )
    return 1


def create_notification(category, message, target_role="all",
                        target_user_id=None, entity_type=None, entity_id=None,
                        priority="medium", dedup_key=None):
    """Public API for other modules to create notifications."""
    _ensure_tables()
    key = dedup_key or f"{category}:{entity_type}:{entity_id}:{datetime.now().strftime('%Y-%m-%d')}"
    return _create_if_new(category, key, message, target_role,
                          target_user_id, entity_type, entity_id, priority)


# ── Table Setup ─────────────────────────────────────────────


def _ensure_tables():
    global _TABLE_ENSURED
    if _TABLE_ENSURED:
        return
    execute_kelava_query("""
        CREATE TABLE IF NOT EXISTS enterprise_notifications (
            id BIGSERIAL PRIMARY KEY,
            category TEXT NOT NULL,
            dedup_key TEXT UNIQUE,
            message TEXT NOT NULL,
            priority TEXT DEFAULT 'medium',
            target_role TEXT,
            target_user_id BIGINT,
            entity_type TEXT,
            entity_id BIGINT,
            read_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)
    execute_kelava_query("CREATE INDEX IF NOT EXISTS idx_notif_target ON enterprise_notifications(target_role, read_at)")
    execute_kelava_query("CREATE INDEX IF NOT EXISTS idx_notif_user ON enterprise_notifications(target_user_id, read_at)")
    execute_kelava_query("CREATE INDEX IF NOT EXISTS idx_notif_dedup ON enterprise_notifications(dedup_key)")
    _TABLE_ENSURED = True
